name: Sandbox TF Plan
on:
  workflow_dispatch:
  push:
    branches:
    - 'feature/**'
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION : us-east-1

jobs:
  terraform-fmt:
    name: 'Terraform Format'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}

    - name: Install TF
      uses: hashicorp/setup-terraform@v3

    - name: Check Format
      run: terraform fmt -check

  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}

    - name: Install TF
      uses: hashicorp/setup-terraform@v3

    - name: List
      run: |
        echo 'checking directory'
        ls

    - name: Initialize TF
      run: terraform init
#        -backend-config="key=terraform.tfstate" \
#        -backend-config="region=eu-west-1"

    - name: Terraform Plan
      run: |
        terraform plan \
        -var-file="*\src\sandbox.tfvars" \
        -out=terraform.tfplan

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: |
          terraform/terraform.tfplan
          terraform/.terraform.lock.hcl
          if-no-files-found: error
    needs: terraform-fmt
