name: Sandbox TF Apply
on: workflow_dispatch

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}

    - name: Install TF
      uses: hashicorp/setup-terraform@v3

#    - name: Download Terraform Plan
#        uses: actions/upload-artifact@v4
#        with:
#          name: tfplan
#          path: |
#            terraform/terraform.tfplan
#            terraform/.terraform.lock.hcl
#            if-no-files-found: error

    - name: Terraform Apply
        run: terraform apply terraform/terraform.tfplan
    needs: terraform-fmt

